const ROLES = {
  ADMIN: 'ADMIN',
  OPERATOR: 'OPERATOR',
  VIEWER: 'VIEWER',
};

const TRANSACTION_TYPES = {
  CASH: 'CASH',
  BON: 'BON',
  ANGGARAN: 'ANGGARAN',
};

const TRANSACTION_STATUS = {
  COMPLETED: 'COMPLETED',
  PENDING: 'PENDING',
  CANCELLED: 'CANCELLED',
};

const MOVEMENT_TYPES = {
  IN: 'IN',
  OUT: 'OUT',
  ADJUSTMENT: 'ADJUSTMENT',
  OPNAME: 'OPNAME',
};

const REFERENCE_TYPES = {
  PO: 'PO',
  TRANSACTION: 'TRANSACTION',
  OPNAME: 'OPNAME',
  MANUAL: 'MANUAL',
};

const PO_STATUS = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  RECEIVED: 'RECEIVED',
  CANCELLED: 'CANCELLED',
};

const PROJECT_STATUS = {
  PLANNING: 'PLANNING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const OPNAME_STATUS = {
  DRAFT: 'DRAFT',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
};

const NOTIFICATION_STATUS = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
};

const DEFAULT_PAGE_SIZE = 20;

// Format label Bahasa Indonesia
const ROLE_LABELS = {
  [ROLES.ADMIN]: 'Administrator',
  [ROLES.OPERATOR]: 'Operator',
  [ROLES.VIEWER]: 'Viewer',
};

const TRANSACTION_TYPE_LABELS = {
  [TRANSACTION_TYPES.CASH]: 'Tunai',
  [TRANSACTION_TYPES.BON]: 'Bon',
  [TRANSACTION_TYPES.ANGGARAN]: 'Anggaran',
};

const TRANSACTION_STATUS_LABELS = {
  [TRANSACTION_STATUS.COMPLETED]: 'Selesai',
  [TRANSACTION_STATUS.PENDING]: 'Tertunda',
  [TRANSACTION_STATUS.CANCELLED]: 'Dibatalkan',
};

const MOVEMENT_TYPE_LABELS = {
  [MOVEMENT_TYPES.IN]: 'Masuk',
  [MOVEMENT_TYPES.OUT]: 'Keluar',
  [MOVEMENT_TYPES.ADJUSTMENT]: 'Penyesuaian',
  [MOVEMENT_TYPES.OPNAME]: 'Opname',
};

const REFERENCE_TYPE_LABELS = {
  [REFERENCE_TYPES.PO]: 'Purchase Order',
  [REFERENCE_TYPES.TRANSACTION]: 'Transaksi',
  [REFERENCE_TYPES.OPNAME]: 'Stock Opname',
  [REFERENCE_TYPES.MANUAL]: 'Manual',
};

const PO_STATUS_LABELS = {
  [PO_STATUS.DRAFT]: 'Draft',
  [PO_STATUS.SENT]: 'Terkirim',
  [PO_STATUS.RECEIVED]: 'Diterima',
  [PO_STATUS.CANCELLED]: 'Dibatalkan',
};

const PROJECT_STATUS_LABELS = {
  [PROJECT_STATUS.PLANNING]: 'Perencanaan',
  [PROJECT_STATUS.IN_PROGRESS]: 'Sedang Berjalan',
  [PROJECT_STATUS.COMPLETED]: 'Selesai',
  [PROJECT_STATUS.CANCELLED]: 'Dibatalkan',
};

const OPNAME_STATUS_LABELS = {
  [OPNAME_STATUS.DRAFT]: 'Draft',
  [OPNAME_STATUS.IN_PROGRESS]: 'Sedang Berjalan',
  [OPNAME_STATUS.COMPLETED]: 'Selesai',
};

const NOTIFICATION_STATUS_LABELS = {
  [NOTIFICATION_STATUS.PENDING]: 'Menunggu',
  [NOTIFICATION_STATUS.SENT]: 'Terkirim',
  [NOTIFICATION_STATUS.FAILED]: 'Gagal',
};

module.exports = {
  ROLES,
  TRANSACTION_TYPES,
  TRANSACTION_STATUS,
  MOVEMENT_TYPES,
  REFERENCE_TYPES,
  PO_STATUS,
  PROJECT_STATUS,
  OPNAME_STATUS,
  NOTIFICATION_STATUS,
  DEFAULT_PAGE_SIZE,
  ROLE_LABELS,
  TRANSACTION_TYPE_LABELS,
  TRANSACTION_STATUS_LABELS,
  MOVEMENT_TYPE_LABELS,
  REFERENCE_TYPE_LABELS,
  PO_STATUS_LABELS,
  PROJECT_STATUS_LABELS,
  OPNAME_STATUS_LABELS,
  NOTIFICATION_STATUS_LABELS,
};
